[2023-03-29T15:55:33.070+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.model_predict scheduled__2023-03-29T15:50:00+00:00 [queued]>
[2023-03-29T15:55:33.128+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.model_predict scheduled__2023-03-29T15:50:00+00:00 [queued]>
[2023-03-29T15:55:33.130+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-29T15:55:33.131+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-03-29T15:55:33.133+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-29T15:55:33.177+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): model_predict> on 2023-03-29 15:50:00+00:00
[2023-03-29T15:55:33.195+0000] {standard_task_runner.py:55} INFO - Started process 3266 to run task
[2023-03-29T15:55:33.207+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'model_predict', 'scheduled__2023-03-29T15:50:00+00:00', '--job-id', '421', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmphzaj7n1b']
[2023-03-29T15:55:33.213+0000] {standard_task_runner.py:83} INFO - Job 421: Subtask model_predict
[2023-03-29T15:55:33.395+0000] {task_command.py:388} INFO - Running <TaskInstance: my_dag.model_predict scheduled__2023-03-29T15:50:00+00:00 [running]> on host e7ec0deaf382
[2023-03-29T15:55:33.806+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=model_predict
AIRFLOW_CTX_EXECUTION_DATE=2023-03-29T15:50:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-29T15:50:00+00:00
[2023-03-29T15:55:37.306+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/google/cloud/bigquery/table.py:1988: UserWarning: A progress bar was requested, but there was an error loading the tqdm library. Please install tqdm to use the progress bar functionality.
  create_bqstorage_client=create_bqstorage_client,

[2023-03-29T15:55:48.625+0000] {gbq.py:352} INFO - Total time taken 14.25 s.
Finished at 2023-03-29 15:55:48.
[2023-03-29T15:55:48.630+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 116, in model_predict
    features[label] = features[label].astype(str)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/series.py", line 942, in __getitem__
    return self._get_value(key)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/series.py", line 1051, in _get_value
    loc = self.index.get_loc(label)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/indexes/range.py", line 388, in get_loc
    raise KeyError(key)
KeyError: 'sex'
[2023-03-29T15:55:48.678+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=my_dag, task_id=model_predict, execution_date=20230329T155000, start_date=20230329T155533, end_date=20230329T155548
[2023-03-29T15:55:48.794+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 421 for task model_predict ('sex'; 3266)
[2023-03-29T15:55:48.969+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-29T15:55:49.047+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
