[2023-03-29T11:40:37.922+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.load_predict scheduled__2023-03-29T11:35:00+00:00 [queued]>
[2023-03-29T11:40:37.943+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.load_predict scheduled__2023-03-29T11:35:00+00:00 [queued]>
[2023-03-29T11:40:37.945+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-29T11:40:37.947+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-03-29T11:40:37.948+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-29T11:40:37.977+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): load_predict> on 2023-03-29 11:35:00+00:00
[2023-03-29T11:40:37.990+0000] {standard_task_runner.py:55} INFO - Started process 1127 to run task
[2023-03-29T11:40:37.997+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'load_predict', 'scheduled__2023-03-29T11:35:00+00:00', '--job-id', '346', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpya5o32ek']
[2023-03-29T11:40:38.001+0000] {standard_task_runner.py:83} INFO - Job 346: Subtask load_predict
[2023-03-29T11:40:38.131+0000] {task_command.py:388} INFO - Running <TaskInstance: my_dag.load_predict scheduled__2023-03-29T11:35:00+00:00 [running]> on host e7ec0deaf382
[2023-03-29T11:40:38.284+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=load_predict
AIRFLOW_CTX_EXECUTION_DATE=2023-03-29T11:35:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-29T11:35:00+00:00
[2023-03-29T11:40:41.188+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/google/cloud/bigquery/table.py:1988: UserWarning: A progress bar was requested, but there was an error loading the tqdm library. Please install tqdm to use the progress bar functionality.
  create_bqstorage_client=create_bqstorage_client,

[2023-03-29T11:40:52.111+0000] {gbq.py:352} INFO - Total time taken 13.62 s.
Finished at 2023-03-29 11:40:52.
[2023-03-29T11:40:52.227+0000] {logging_mixin.py:137} INFO -         age  sex  ...                                education tax_filer_status
0         0    1  ...                                 Children         - 50000.
1         0    1  ...                                 Children         - 50000.
2         0    0  ...                                 Children         - 50000.
3         0    1  ...                                 Children         - 50000.
4         0    1  ...                                 Children         - 50000.
...     ...  ...  ...                                      ...              ...
199517   90    1  ...   Prof school degree (MD DDS DVM LLB JD)         - 50000.
199518   90    1  ...   Prof school degree (MD DDS DVM LLB JD)         - 50000.
199519   90    0  ...   Prof school degree (MD DDS DVM LLB JD)          50000+.
199520   90    1  ...   Prof school degree (MD DDS DVM LLB JD)         - 50000.
199521   90    0  ...   Prof school degree (MD DDS DVM LLB JD)          50000+.

[199522 rows x 5 columns]
[2023-03-29T11:40:54.826+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas_gbq/load.py", line 136, in load_parquet
    project=billing_project,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 2675, in load_table_from_dataframe
    parquet_use_compliant_nested_type=True,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/_pandas_helpers.py", line 586, in dataframe_to_parquet
    arrow_table = dataframe_to_arrow(dataframe, bq_schema)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/_pandas_helpers.py", line 529, in dataframe_to_arrow
    bq_to_arrow_array(get_column_or_index(dataframe, bq_field.name), bq_field)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/_pandas_helpers.py", line 290, in bq_to_arrow_array
    return pyarrow.Array.from_pandas(series, type=arrow_type)
  File "pyarrow/array.pxi", line 1037, in pyarrow.lib.Array.from_pandas
  File "pyarrow/array.pxi", line 313, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 83, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Could not convert ' Never married' with type str: tried to convert to int64

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 135, in transform_tax
    {'name':'tax_filer_status','type': 'INTEGER'}
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas_gbq/gbq.py", line 1205, in to_gbq
    billing_project=project_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas_gbq/gbq.py", line 599, in load_data
    billing_project=billing_project,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas_gbq/load.py", line 246, in load_chunks
    billing_project=billing_project,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas_gbq/load.py", line 141, in load_parquet
    ) from exc
pandas_gbq.exceptions.ConversionError: Could not convert DataFrame to Parquet.
[2023-03-29T11:40:54.848+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=my_dag, task_id=load_predict, execution_date=20230329T113500, start_date=20230329T114037, end_date=20230329T114054
[2023-03-29T11:40:54.870+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 346 for task load_predict (Could not convert DataFrame to Parquet.; 1127)
[2023-03-29T11:40:54.935+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-29T11:40:54.969+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
