[2023-03-29T11:15:10.412+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.extract_and_load scheduled__2023-03-29T11:00:00+00:00 [queued]>
[2023-03-29T11:15:10.744+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.extract_and_load scheduled__2023-03-29T11:00:00+00:00 [queued]>
[2023-03-29T11:15:10.747+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-29T11:15:10.749+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-03-29T11:15:10.750+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-29T11:15:11.058+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): extract_and_load> on 2023-03-29 11:00:00+00:00
[2023-03-29T11:15:11.112+0000] {standard_task_runner.py:55} INFO - Started process 612 to run task
[2023-03-29T11:15:11.212+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'extract_and_load', 'scheduled__2023-03-29T11:00:00+00:00', '--job-id', '325', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp9mintafj']
[2023-03-29T11:15:11.328+0000] {standard_task_runner.py:83} INFO - Job 325: Subtask extract_and_load
[2023-03-29T11:15:12.720+0000] {task_command.py:388} INFO - Running <TaskInstance: my_dag.extract_and_load scheduled__2023-03-29T11:00:00+00:00 [running]> on host e7ec0deaf382
[2023-03-29T11:15:13.498+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=extract_and_load
AIRFLOW_CTX_EXECUTION_DATE=2023-03-29T11:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-29T11:00:00+00:00
[2023-03-29T11:15:13.513+0000] {logging_mixin.py:137} INFO - eeeee test-chronotruck test-chr-ml/primary/data.csv
[2023-03-29T11:15:30.428+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 72, in load_csv_from_bucket
    df = pd.read_csv(filename, index_col=None, sep=",")
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 488, in _read
    return parser.read(nrows)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1047, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 224, in read
    chunks = self._reader.read_low_memory(nrows)
  File "pandas/_libs/parsers.pyx", line 801, in pandas._libs.parsers.TextReader.read_low_memory
  File "pandas/_libs/parsers.pyx", line 857, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 843, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1925, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 42 fields in line 10446, saw 58

[2023-03-29T11:15:30.576+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=my_dag, task_id=extract_and_load, execution_date=20230329T110000, start_date=20230329T111510, end_date=20230329T111530
[2023-03-29T11:15:30.809+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 325 for task extract_and_load (Error tokenizing data. C error: Expected 42 fields in line 10446, saw 58
; 612)
[2023-03-29T11:15:30.922+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-29T11:15:31.307+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
