[2023-03-29T18:40:05.647+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.extract_and_load scheduled__2023-03-29T18:30:00+00:00 [queued]>
[2023-03-29T18:40:05.776+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.extract_and_load scheduled__2023-03-29T18:30:00+00:00 [queued]>
[2023-03-29T18:40:05.777+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-29T18:40:05.782+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-03-29T18:40:05.785+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-29T18:40:05.985+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): extract_and_load> on 2023-03-29 18:30:00+00:00
[2023-03-29T18:40:06.065+0000] {standard_task_runner.py:55} INFO - Started process 307 to run task
[2023-03-29T18:40:06.104+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'extract_and_load', 'scheduled__2023-03-29T18:30:00+00:00', '--job-id', '465', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmphcil59c7']
[2023-03-29T18:40:06.133+0000] {standard_task_runner.py:83} INFO - Job 465: Subtask extract_and_load
[2023-03-29T18:40:08.146+0000] {task_command.py:388} INFO - Running <TaskInstance: my_dag.extract_and_load scheduled__2023-03-29T18:30:00+00:00 [running]> on host 32688d23169d
[2023-03-29T18:40:09.437+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=extract_and_load
AIRFLOW_CTX_EXECUTION_DATE=2023-03-29T18:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-29T18:30:00+00:00
[2023-03-29T18:40:09.506+0000] {logging_mixin.py:137} INFO - eeeee test-chronotruck test-chr-ml/primary/data.csv
[2023-03-29T18:41:06.284+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 73, in load_csv_from_bucket
    features=df.iloc[:, [0,12,7,4,41]]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/indexing.py", line 925, in __getitem__
    return self._getitem_tuple(key)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/indexing.py", line 1506, in _getitem_tuple
    self._has_valid_tuple(tup)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/indexing.py", line 754, in _has_valid_tuple
    self._validate_key(k, i)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/indexing.py", line 1424, in _validate_key
    raise IndexError("positional indexers are out-of-bounds")
IndexError: positional indexers are out-of-bounds
[2023-03-29T18:41:06.459+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=my_dag, task_id=extract_and_load, execution_date=20230329T183000, start_date=20230329T184005, end_date=20230329T184106
[2023-03-29T18:41:06.895+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 465 for task extract_and_load (positional indexers are out-of-bounds; 307)
[2023-03-29T18:41:08.110+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-29T18:41:10.646+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
