[2023-03-29T15:45:25.190+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.model_predict scheduled__2023-03-29T15:40:00+00:00 [queued]>
[2023-03-29T15:45:25.215+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.model_predict scheduled__2023-03-29T15:40:00+00:00 [queued]>
[2023-03-29T15:45:25.216+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-29T15:45:25.218+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-03-29T15:45:25.220+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-29T15:45:25.273+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): model_predict> on 2023-03-29 15:40:00+00:00
[2023-03-29T15:45:25.295+0000] {standard_task_runner.py:55} INFO - Started process 3065 to run task
[2023-03-29T15:45:25.310+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'model_predict', 'scheduled__2023-03-29T15:40:00+00:00', '--job-id', '414', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpdn4d1b1r']
[2023-03-29T15:45:25.315+0000] {standard_task_runner.py:83} INFO - Job 414: Subtask model_predict
[2023-03-29T15:45:25.488+0000] {task_command.py:388} INFO - Running <TaskInstance: my_dag.model_predict scheduled__2023-03-29T15:40:00+00:00 [running]> on host e7ec0deaf382
[2023-03-29T15:45:25.652+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=model_predict
AIRFLOW_CTX_EXECUTION_DATE=2023-03-29T15:40:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-29T15:40:00+00:00
[2023-03-29T15:45:28.426+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/google/cloud/bigquery/table.py:1988: UserWarning: A progress bar was requested, but there was an error loading the tqdm library. Please install tqdm to use the progress bar functionality.
  create_bqstorage_client=create_bqstorage_client,

[2023-03-29T15:45:39.345+0000] {gbq.py:352} INFO - Total time taken 13.51 s.
Finished at 2023-03-29 15:45:39.
[2023-03-29T15:45:39.348+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 116, in model_predict
    features[label] = features[label].astype(str)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/series.py", line 942, in __getitem__
    return self._get_value(key)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/series.py", line 1051, in _get_value
    loc = self.index.get_loc(label)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/indexes/range.py", line 388, in get_loc
    raise KeyError(key)
KeyError: 'sex'
[2023-03-29T15:45:39.377+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=my_dag, task_id=model_predict, execution_date=20230329T154000, start_date=20230329T154525, end_date=20230329T154539
[2023-03-29T15:45:39.405+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 414 for task model_predict ('sex'; 3065)
[2023-03-29T15:45:39.481+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-29T15:45:39.514+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
