[2023-03-29T00:45:46.370+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.load_predict scheduled__2023-03-29T00:40:00+00:00 [queued]>
[2023-03-29T00:45:46.398+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.load_predict scheduled__2023-03-29T00:40:00+00:00 [queued]>
[2023-03-29T00:45:46.400+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-29T00:45:46.402+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-03-29T00:45:46.404+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-29T00:45:46.436+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): load_predict> on 2023-03-29 00:40:00+00:00
[2023-03-29T00:45:46.452+0000] {standard_task_runner.py:55} INFO - Started process 604 to run task
[2023-03-29T00:45:46.462+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'load_predict', 'scheduled__2023-03-29T00:40:00+00:00', '--job-id', '278', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpolezob8n']
[2023-03-29T00:45:46.468+0000] {standard_task_runner.py:83} INFO - Job 278: Subtask load_predict
[2023-03-29T00:45:46.600+0000] {task_command.py:388} INFO - Running <TaskInstance: my_dag.load_predict scheduled__2023-03-29T00:40:00+00:00 [running]> on host 18cf4662f3ac
[2023-03-29T00:45:46.771+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=load_predict
AIRFLOW_CTX_EXECUTION_DATE=2023-03-29T00:40:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-29T00:40:00+00:00
[2023-03-29T00:45:51.277+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/google/cloud/bigquery/table.py:1988: UserWarning: A progress bar was requested, but there was an error loading the tqdm library. Please install tqdm to use the progress bar functionality.
  create_bqstorage_client=create_bqstorage_client,

[2023-03-29T00:47:43.169+0000] {gbq.py:352} INFO - Total time taken 116.26 s.
Finished at 2023-03-29 00:47:43.
[2023-03-29T00:47:43.264+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 110, in transform_tax
    encoder = LabelEncoder()
NameError: name 'LabelEncoder' is not defined
[2023-03-29T00:47:43.294+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=my_dag, task_id=load_predict, execution_date=20230329T004000, start_date=20230329T004546, end_date=20230329T004743
[2023-03-29T00:47:43.328+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 278 for task load_predict (name 'LabelEncoder' is not defined; 604)
[2023-03-29T00:47:43.443+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-29T00:47:43.478+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
