[2023-03-29T01:41:31.664+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.extract_and_load scheduled__2023-03-29T01:35:00+00:00 [queued]>
[2023-03-29T01:41:31.712+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.extract_and_load scheduled__2023-03-29T01:35:00+00:00 [queued]>
[2023-03-29T01:41:31.714+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-29T01:41:31.715+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-03-29T01:41:31.717+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-29T01:41:31.834+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): extract_and_load> on 2023-03-29 01:35:00+00:00
[2023-03-29T01:41:31.890+0000] {standard_task_runner.py:55} INFO - Started process 1087 to run task
[2023-03-29T01:41:31.972+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'extract_and_load', 'scheduled__2023-03-29T01:35:00+00:00', '--job-id', '289', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpaskxr465']
[2023-03-29T01:41:31.991+0000] {standard_task_runner.py:83} INFO - Job 289: Subtask extract_and_load
[2023-03-29T01:41:32.286+0000] {task_command.py:388} INFO - Running <TaskInstance: my_dag.extract_and_load scheduled__2023-03-29T01:35:00+00:00 [running]> on host 18cf4662f3ac
[2023-03-29T01:41:33.113+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=extract_and_load
AIRFLOW_CTX_EXECUTION_DATE=2023-03-29T01:35:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-29T01:35:00+00:00
[2023-03-29T01:41:33.134+0000] {logging_mixin.py:137} INFO - eeeee test-chronotruck test-chr-ml/primary/data.csv
[2023-03-29T01:59:11.729+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 66, in load_csv_from_bucket
    blob.download_to_filename("/tmp/" + filename)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 1280, in download_to_filename
    os.utime(file_obj.name, (mtime, mtime))
FileNotFoundError: [Errno 2] No such file or directory
[2023-03-29T01:59:15.726+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=my_dag, task_id=extract_and_load, execution_date=20230329T013500, start_date=20230329T014131, end_date=20230329T015915
[2023-03-29T01:59:16.435+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 289 for task extract_and_load ([Errno 2] No such file or directory; 1087)
[2023-03-29T01:59:18.628+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-29T01:59:19.310+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
