[2023-03-29T17:05:38.068+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.model_predict scheduled__2023-03-29T17:00:00+00:00 [queued]>
[2023-03-29T17:05:38.093+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.model_predict scheduled__2023-03-29T17:00:00+00:00 [queued]>
[2023-03-29T17:05:38.095+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-29T17:05:38.098+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-03-29T17:05:38.100+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-29T17:05:38.138+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): model_predict> on 2023-03-29 17:00:00+00:00
[2023-03-29T17:05:38.149+0000] {standard_task_runner.py:55} INFO - Started process 398 to run task
[2023-03-29T17:05:38.165+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'model_predict', 'scheduled__2023-03-29T17:00:00+00:00', '--job-id', '446', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmppw6bvlzb']
[2023-03-29T17:05:38.170+0000] {standard_task_runner.py:83} INFO - Job 446: Subtask model_predict
[2023-03-29T17:05:38.340+0000] {task_command.py:388} INFO - Running <TaskInstance: my_dag.model_predict scheduled__2023-03-29T17:00:00+00:00 [running]> on host c9ad826755ad
[2023-03-29T17:05:38.512+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=model_predict
AIRFLOW_CTX_EXECUTION_DATE=2023-03-29T17:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-29T17:00:00+00:00
[2023-03-29T17:05:41.798+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/google/cloud/bigquery/table.py:1988: UserWarning: A progress bar was requested, but there was an error loading the tqdm library. Please install tqdm to use the progress bar functionality.
  create_bqstorage_client=create_bqstorage_client,

[2023-03-29T17:05:50.609+0000] {gbq.py:352} INFO - Total time taken 11.84 s.
Finished at 2023-03-29 17:05:50.
[2023-03-29T17:05:51.501+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 116, in model_predict
    model=pickle.load(open('/opt/airflow/data/model.pkl','rb'))
  File "/home/airflow/.local/lib/python3.7/site-packages/lightgbm/__init__.py", line 8, in <module>
    from .basic import Booster, Dataset, Sequence, register_logger
  File "/home/airflow/.local/lib/python3.7/site-packages/lightgbm/basic.py", line 110, in <module>
    _LIB = _load_lib()
  File "/home/airflow/.local/lib/python3.7/site-packages/lightgbm/basic.py", line 101, in _load_lib
    lib = ctypes.cdll.LoadLibrary(lib_path[0])
  File "/usr/local/lib/python3.7/ctypes/__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "/usr/local/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libgomp.so.1: cannot open shared object file: No such file or directory
[2023-03-29T17:05:51.548+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=my_dag, task_id=model_predict, execution_date=20230329T170000, start_date=20230329T170538, end_date=20230329T170551
[2023-03-29T17:05:51.610+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 446 for task model_predict (libgomp.so.1: cannot open shared object file: No such file or directory; 398)
[2023-03-29T17:05:51.695+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-29T17:05:51.792+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
