[2023-03-29T15:55:06.051+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.send_email scheduled__2023-03-29T15:50:00+00:00 [queued]>
[2023-03-29T15:55:06.075+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.send_email scheduled__2023-03-29T15:50:00+00:00 [queued]>
[2023-03-29T15:55:06.077+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-29T15:55:06.079+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-03-29T15:55:06.081+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-29T15:55:06.129+0000] {taskinstance.py:1303} INFO - Executing <Task(EmailOperator): send_email> on 2023-03-29 15:50:00+00:00
[2023-03-29T15:55:06.148+0000] {standard_task_runner.py:55} INFO - Started process 3250 to run task
[2023-03-29T15:55:06.167+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'send_email', 'scheduled__2023-03-29T15:50:00+00:00', '--job-id', '419', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpy2mfperi']
[2023-03-29T15:55:06.172+0000] {standard_task_runner.py:83} INFO - Job 419: Subtask send_email
[2023-03-29T15:55:06.374+0000] {task_command.py:388} INFO - Running <TaskInstance: my_dag.send_email scheduled__2023-03-29T15:50:00+00:00 [running]> on host e7ec0deaf382
[2023-03-29T15:55:06.575+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=send_email
AIRFLOW_CTX_EXECUTION_DATE=2023-03-29T15:50:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-29T15:50:00+00:00
[2023-03-29T15:55:06.674+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/email.py:152: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2023-03-29T15:55:06.686+0000] {configuration.py:664} WARNING - section/key [smtp/smtp_user] not found in config
[2023-03-29T15:55:06.694+0000] {email.py:268} INFO - Email alerting: attempt 1
[2023-03-29T15:55:06.704+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/email.py", line 87, in execute
    custom_headers=self.custom_headers,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 91, in send_email
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 152, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 270, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 317, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2023-03-29T15:55:06.813+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=my_dag, task_id=send_email, execution_date=20230329T155000, start_date=20230329T155506, end_date=20230329T155506
[2023-03-29T15:55:06.916+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 419 for task send_email ([Errno 99] Cannot assign requested address; 3250)
[2023-03-29T15:55:06.991+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-29T15:55:07.165+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
