[2023-03-28T15:15:03.557+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.extract_and_load scheduled__2023-03-28T15:10:00+00:00 [queued]>
[2023-03-28T15:15:03.589+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.extract_and_load scheduled__2023-03-28T15:10:00+00:00 [queued]>
[2023-03-28T15:15:03.592+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-28T15:15:03.594+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-03-28T15:15:03.596+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-28T15:15:03.637+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): extract_and_load> on 2023-03-28 15:10:00+00:00
[2023-03-28T15:15:03.651+0000] {standard_task_runner.py:55} INFO - Started process 1047 to run task
[2023-03-28T15:15:03.686+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'extract_and_load', 'scheduled__2023-03-28T15:10:00+00:00', '--job-id', '121', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp2lgibxmt']
[2023-03-28T15:15:03.694+0000] {standard_task_runner.py:83} INFO - Job 121: Subtask extract_and_load
[2023-03-28T15:15:04.040+0000] {task_command.py:388} INFO - Running <TaskInstance: my_dag.extract_and_load scheduled__2023-03-28T15:10:00+00:00 [running]> on host e77fd029e562
[2023-03-28T15:15:04.318+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=extract_and_load
AIRFLOW_CTX_EXECUTION_DATE=2023-03-28T15:10:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-28T15:10:00+00:00
[2023-03-28T15:15:04.341+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 67, in load
    df=pd.read_csv("/Users/macbook/Documents/ibrahima/vs-airflow-demo/data/census_income_learn.csv")
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/Users/macbook/Documents/ibrahima/vs-airflow-demo/data/census_income_learn.csv'
[2023-03-28T15:15:04.434+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=my_dag, task_id=extract_and_load, execution_date=20230328T151000, start_date=20230328T151503, end_date=20230328T151504
[2023-03-28T15:15:04.495+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 121 for task extract_and_load ([Errno 2] No such file or directory: '/Users/macbook/Documents/ibrahima/vs-airflow-demo/data/census_income_learn.csv'; 1047)
[2023-03-28T15:15:04.555+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-28T15:15:04.636+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
